sudo: required

services:
  - docker

git:
  depth: 1

script:
- docker build -t rainbond/buildpack-requirements:cedar-14 buildpack
- docker run --rm -v ${PWD}/lang:/offline rainbond/buildpack-requirements:cedar-14 dev common,php
- sudo chmod -R 755 ${PWD}/lang
- docker build -t rainbond/buildpack:$TRAVIS_BRANCH-v5.0 .
- docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
- docker push rainbond/buildpack:$TRAVIS_BRANCH-v5.0




