sudo: required

services:
  - docker

git:
  depth: 1

script:
- docker build -t rainbond/buildpack-requirements:cedar-14 buildpack
- docker run --rm -v ${PWD}/lang:/offline rainbond/buildpack-requirements:cedar-14
- sudo chmod -R 755 ${PWD}/lang
- docker build -t rainbond/buildpack:all-$TRAVIS_BRANCH .
- docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
- docker push rainbond/buildpack:all-$TRAVIS_BRANCH 
- docker push rainbond/buildpack-requirements:cedar-14
