FROM debian:9.5

RUN sed -i 's/deb.debian.org/mirrors.ustc.edu.cn/g' /etc/apt/sources.list && apt update && apt-get install --no-install-recommends --no-install-suggests -y apt-transport-https ca-certificates procps net-tools curl wget jq && \
    rm -rf /var/lib/apt/lists/* 

ADD download.sh /download.sh

COPY language /language

RUN chmod +x /download.sh

ENTRYPOINT [ "/download.sh" ]