#!/bin/bash

VENDOR_URL="http://buildpack.rainbond.com/java"

download_path="/offline/java/"
java_base=(jvm.tgz stdlib.sh pgconfig.jar)
java_jdks=(openjdk1.6.0_27.tar.gz openjdk1.7.0_181.tar.gz openjdk1.8.0_171.tar.gz openjdk10.0.1.tar.gz openjdk11-ea-24.tar.gz openjdk9.0.4.tar.gz)
java_maven_versions=(3.0.5 3.1.1 3.2.3 3.2.5 3.3.9)

# check download path
[ -d "$download_path" ] || mkdir -p $download_path

# download pkg

pushd $download_path
for pkg in ${java_base[@]}
do
    echo "download ${VENDOR_URL}/${pkg}"
    wget -q ${VENDOR_URL}/${pkg}
done
popd

# download jdk
echo "download all jdk"
[ -d "$download_path/jdk" ] || mkdir -p $download_path/jdk
pushd $download_path/jdk
for jdk in ${java_jdks[@]}
do
    echo "download ${VENDOR_URL}/${jdk}"
    wget -q  ${VENDOR_URL}/${jdk}
done
popd


# download maven
echo "download all maven"
[ -d "$download_path/maven" ] || mkdir -p $download_path/maven
pushd $download_path/maven
for maven in ${java_maven_versions[@]}
do
    echo "download ${VENDOR_URL}/maven-${maven}.tar.gz"
    wget -q  ${VENDOR_URL}/maven-${maven}.tar.gz
done
popd